feat: add a variety of graph indicators
dendronhq/dendron pull request #1024
Opened 2021-07-23 16:50 UTC by hfellerhoff

Adds/changes:
- A loading indicator on graph startup
- A loading indicator when changing between local/full note graphs
- A message when local graph has no active note, with a button to toggle to view the full graph
- Better graph config view hiding/showing

2021-07-24 16:17 UTC, kevinslin requested changes
there is an error when toggling from the full graph to local and back again

https://www.loom.com/share/a3887e1455c1420eb2d9e9514f180580

2021-07-24 17:02 UTC, hfellerhoff commented
> there is an error when toggling from the full graph to local and back again
> 
> 
> 
> https://www.loom.com/share/a3887e1455c1420eb2d9e9514f180580

Yeah, this is something I touched on I think in another PR - this error is thrown (I believe) when the graph gets a request to re-render and hasn't finished its previous render. It doesn't affect the final output, and actually won't show up at all in a production build or affect the rendered graph.

2021-07-24 17:49 UTC, kevinslin commented
Can we block the request while a render is in flight?

On Sat, Jul 24, 2021 at 10:02 AM hfellerhoff ***@***.***>
wrote:

> there is an error when toggling from the full graph to local and back again
>
> https://www.loom.com/share/a3887e1455c1420eb2d9e9514f180580
>
> Yeah, this is something I touched on I think in another PR - this error is
> thrown (I believe) when the graph gets a request to re-render and hasn't
> finished its previous render. It doesn't affect the final output, and
> actually won't show up at all in a production build or affect the rendered
> graph.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dendronhq/dendron/pull/1024#issuecomment-886080629>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AADD52ILQXNR62TI76CAS4TTZLWZXANCNFSM5A4KY4VQ>
> .
>

2021-07-26 09:32 UTC, namjul commented on .eslintrc.js
> +    "react/jsx-filename-extension": "off",
What is the aim of turning this rule off? I think it should only apply for `jsx` files and we don't use them. For typescript files we want to force using `tsx` extension. Do we want the same for js. In any case can you extend the comment to explicate it more.

About the word explication I find the following article giving good insights https://mindlevelup.wordpress.com/2017/07/15/explication/. Sharing resources ;)

2021-07-27 17:07 UTC, kevinslin commented
looks like there's some conflicts with master here

2021-07-28 17:34 UTC, kevinslin approved these changes

2021-07-28 17:34 UTC, merged