fix: hashtags include punctuation and quotation marks
dendronhq/dendron pull request #1054
Opened 2021-07-28 20:54 UTC by SeriousBug

Hashtags are now not allowed to contain any punctuation or quotation marks. This allows them to be more easily mixed into text, for example:

```
This issue is #important, and should be prioritized.

This issue is #important. It should be prioritized.

They said "This issue is #important", so it should be prioritized.
```

In all these examples, the tag is `#important` without the following marks.

#1048

2021-07-28 21:12 UTC, kevinslin requested changes
for hashtags, we actually want to include `.` since `#foo.bar` is an acceptable tag in dendron land

2021-07-28 21:16 UTC, SeriousBug commented
> for hashtags, we actually want to include `.` since `#foo.bar` is an acceptable tag in dendron land

Periods are handled as a special case, only trailing periods are ignored. For example `#foo.bar` is "foo.bar" but `#foo.` is only "foo". 

I'll check out the failing tests in a bit, they looked fine on my end.

2021-07-28 22:43 UTC, SeriousBug commented
I checked and we already had a test that includes a hierarchy (`#my.hash.tag0`).

It's very interesting that the Windows tests are failing the way they do. It suggests that the regular expressions are not working in the same way in Windows and other versions. I'll see what I can find about this.

2021-07-28 22:56 UTC, kevinslin commented
you're right, missed that. for the windows regex issue, feel free to leave that to me. i'll have some time tomorrow to debug and it's a lot easier with a windows machine. in the future, we'll also have a windows vm for the team to ssh into to debug these sorts of issues

2021-07-30 17:59 UTC, kevinslin approved these changes

2021-07-30 17:59 UTC, merged