spike: add luxon based config generator
dendronhq/dendron pull request #1065
Opened 2021-07-30 13:32 UTC by namjul

2021-08-03 17:59 UTC, kevinslin requested changes
- heads up that we need to remove the following lines since we are now supporting journals
```ts
  if (engine.config?.journal.dateFormat !== "y.MM.dd") {
    return genError(
      `only "journal.dateFormat:"y.MM.dd" is supported currently`
    );
  }
  if (engine.config?.journal.addBehavior !== "childOfDomain") {
    return genError(
      `only "journal.addBehavior = "childOfDomain" is supported currently`
    );
  }
  if (engine.config?.journal.dailyDomain !== "daily") {
    return genError(
      `only "journal.dailyDomain = "daily" is supported currently`
    );
  }
  if (engine.config?.journal.name !== "journal") {
    return genError(`only "journal.name = "name" is supported currently`);
  }
```

- we also need to remove hardcoded values like the following in line 161
```ts
postVSCodeMessage({
  type: CalendarViewMessageType.onSelect,
  data: {
    id: selectedNote?.id,
    fname: `daily.journal.${dateKey}`,
  },
  source: DMessageSource.webClient,
});
```

- can we do a test of the calendar with the following configurations?
  - journal.dateFormat: change year, month, and day component
  - journal.addBehavior: change to other [add behavior](https://wiki.dendron.so/notes/5c213aa6-e4ba-49e8-85c5-1bdcb33ce202.html#defaultnodetypeaddbehavior) and see if it works
  - journal.dailyDomain: change to non default value
  - journal.name: change to non default value

2021-08-03 17:59 UTC, kevinslin commented on packages/dendron-next-server/pages/vscode/calendar-view.tsx
> +      const isMontly = maybeDatePortion.split(".").length === 2;
nitpick: spelling. `isMonthly`

2021-08-04 11:23 UTC, namjul commented on packages/dendron-next-server/pages/vscode/calendar-view.tsx
> +      const isMontly = maybeDatePortion.split(".").length === 2;
[`872a5ef` (#1065)](https://github.com/dendronhq/dendron/pull/1065/commits/872a5ef4c434facd0bef3f63692c4218571e0883)

2021-08-06 17:29 UTC, kevinslin approved these changes

2021-08-06 17:29 UTC, merged