chore: bad `expect` in plugin tests
dendronhq/dendron pull request #1098
Opened 2021-08-05 06:08 UTC by SeriousBug

Tests in `engine-server/rename.ts` were being run in the plugin, which was then failing because the `expect` is not defined. The failed tests would print out errors, but would still pass.

I worked around the failure, another alternative would be to completely strip out the `expect` or avoid the `checkFile` functions in `rename.ts` tests. I haven't investigated why the tests were passing despite the error.

2021-08-05 16:36 UTC, kevinslin requested changes
can you verify if this is still the case?

checked https://github.com/dendronhq/dendron/blob/master/packages/engine-test-utils/src/presets/engine-server/rename.ts#L22:L22

and don't see any calls to `check*` functions in the current version of master

2021-08-05 20:13 UTC, SeriousBug commented
It's the [`checkFile`](https://github.com/dendronhq/dendron/blob/master/packages/engine-test-utils/src/presets/engine-server/rename.ts#L884) function, which then calls `checkString` and `checkNotInString`.

2021-08-05 22:08 UTC, kevinslin commented
Ah, I see. Instead of swallowing the error, can we create a new function `checkFileNoExpect` that returns true/false if the check passes?

2021-08-06 13:56 UTC, kevinslin approved these changes

2021-08-06 13:56 UTC, merged