fix: issue with direct child filter partially omitting values in quickpick
dendronhq/dendron pull request #1123
Opened 2021-08-10 13:30 UTC by hikchoi

This PR:
- Fixes an issue in Lookup (v2) where the direct child filter would be applied _after_ pagination has happened, which allowed some values to be omitted from the selectable items.
- Adds example notes that demonstrate the fix.

2021-08-10 18:54 UTC, kevinslin requested changes
we should also fix this issue in LookupProviderV3 since that will be the default soon. you'll need to do the check [here](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/components/lookup/utils.ts#L703:L703)

2021-08-12 01:38 UTC, jonathanyeung commented
lgtm for v2 changes

2021-08-12 11:08 UTC, hikchoi commented
This PR also:
- fixes a bug where triggering the direct child filter button would revert the picker value change to initial value
- changes picker refresh behavior to 
  - only refresh buttons that needs to be refreshed
    - this change broke the behavior of note type modifiers, which has also been fixed.
  - properly refresh picker after direct child filter is triggered

2021-08-12 14:44 UTC, hikchoi commented
fyi: #1135 is branched off of this PR so this one should go in first.

2021-08-13 00:25 UTC, kevinslin approved these changes

2021-08-13 00:25 UTC, merged