chore: pull request template
dendronhq/dendron pull request #1247
Opened 2021-08-31 15:44 UTC by kevinslin

2021-08-31 16:19 UTC, hikchoi requested changes
Fixed some links but other than that looks good.

2021-08-31 16:19 UTC, hikchoi commented on pull_request_template.md
> +- [ ] do a spot check by running your feature with our [test Workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
nitpick: 
```suggestion
- [ ] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
```

2021-08-31 16:19 UTC, hikchoi commented on pull_request_template.md
> +- [ ] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
Wrong link
```suggestion
- [ ] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
```

2021-08-31 16:19 UTC, hikchoi commented on pull_request_template.md
> +- [ ] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://github.com/dendronhq/dendron/blob/feat/has
the link 404s. maybe you meant this?: 
```suggestion
- [ ] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually inspect new changes and for auto regression testiing 
```

2021-08-31 16:19 UTC, hikchoi commented on pull_request_template.md
> +- [ ] if you are adding analytics related changes, make sure the [Telemetry](dendron.ref.telemetry) docs are updated
```suggestion
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated
```

2021-08-31 16:29 UTC, hikchoi approved these changes

2021-09-02 00:13 UTC, kevinslin commented
> Can we add a line in there for release note description?
> 
> Something along the lines of
> 
> > If this is a user-facing feature or may the overall Dendron experience, please summarize the feature or impact in 1-2 lines for the changelog release notes. If this builds upon a previous PR covering the same area, please link to that PR instead.

made some updates

2021-09-02 03:13 UTC, jonathanyeung approved these changes

2021-09-02 04:56 UTC, merged