Fix/markdown import to update asset links
dendronhq/dendron pull request #1265
Opened 2021-09-01 19:36 UTC by Harshita-mindfire

2021-09-06 07:51 UTC, jonathanyeung requested changes
See prev. comment about being consistent on `/` slashes. Thanks!

2021-09-06 08:42 UTC, Harshita-mindfire commented
> I notice in the loom video that in the imported note the path has a mix of back and forward slashes. Can we normalize to all forward `/` slashes?

This might be the case for windows only, should I replace all `\` with '/' then?

2021-09-09 08:00 UTC, SeriousBug reviewed
Small nitpicks, looks good.

2021-09-10 02:27 UTC, jonathanyeung approved these changes

2021-09-10 02:27 UTC, merged