enhance: conditionally bubble up create new & allow queries longer than fname when special chars are used.
dendronhq/dendron pull request #1308
Opened 2021-09-08 10:37 UTC by nickolay-kondratyev

# Conditionally bubble up create new and allow longer queries than file name searched when special chars are used.
When special characters are not used bubble up create new entry, and allow queries that are longer than file names searched when special characters are used. For this change allows 'hi world !bye' to match 'hi.world'

# Addresses
* [[ scratch.2021.09.08.121701.lookup-bubble-up-create-new-when-no-exact-match-and-no-special-characters]]
* [[scratch.2021.09.07.213159.improve-look-up-do-not-count-special-chars-for-hiding-results]]

# Note 
As mentioned in the comments our current & previous behavior allows creation of notes that can be confusing for FuseJS to look up. For example we can create a note 'hi$world' but if we query for just dollar sign '$' FuseJS will not look up 'hi$world' since '$' will be treated as special character according to https://fusejs.io/examples.html#extended-search rules. 'hi$world' can still be matched by 'hi world'. Given that we don't know if our users have such characters in their files not disabling creation of such files in this PR but it is something for us to think about. 

# Pull Request Checklist

## General

### Quality Assurance
- [x] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [x] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [x] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [ ] after you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
  - NOTE: if you running mac/linux, check the windows output and vice versa if you are developing on windows

2021-09-08 14:19 UTC, kevinslin requested changes
Changes look good, can you also update the docs here -> [[Summary|dendron.topic.lookup.create#summary]] to describe this behavior?

2021-09-08 14:28 UTC, hikchoi approved these changes
lgtm. +1 on the point that we should have docs about special queries.

2021-09-10 05:54 UTC, nickolay-kondratyev commented
Updated the docs to describe bubble up behavior https://github.com/dendronhq/dendron-site/pull/191

On the point of special queries documentation we have FuseJS extended search documentation linked in Lookup note documentation https://wiki.dendron.so/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.html but we can expand upon their doc to make the special queries syntax be more visible in our documentation.

2021-09-11 14:23 UTC, kevinslin approved these changes

2021-09-11 14:23 UTC, merged