Feat/error reporting
dendronhq/dendron pull request #1327
Opened 2021-09-12 15:35 UTC by jonathanyeung

# Pull Request Checklist

You can go to [dendron pull requests](https://wiki.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html) to see full details for items in this checklist.

## General

### Quality Assurance
- [ ] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [ ] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [ ] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [ ] after you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
  - NOTE: if you running mac/linux, check the windows output and vice versa if you are developing on windows

#### Special Cases
- [ ] if your tests changes an existing snaphot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [ ] if you are adding a new language feature (graphically visible in vscode/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually inspect new changes and for auto regression testiing 

### Docs
- [ ] Make sure that the PR title follows our [commit style](https://wiki.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html#commit-style)
- [ ] Please summarize the feature or impact in 1-2 lines in the PR description
- [ ] If your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR

Example PR Description
```markdown
# feat: capitalize all foos

This changes capitalizes all occurences of `foo` to `Foo` 

Docs PR: <URL_TO_DOCS_PR>
```

## Special Cases

### First Time PR
- [ ] sign the [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) which will be prompted by our github bot after you submit the PR
- [ ] add your [discord](https://discord.gg/AE3NRw9) alias in the review so that we can give you the [horticulturalist](https://wiki.dendron.so/notes/7c00d606-7b75-4d28-b563-d75f33f8e0d7.html#horticulturalist) badge in our community

### Analytics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

2021-09-12 15:36 UTC, jonathanyeung commented on packages/common-server/src/analytics.ts
> +    //TODO: respect user's telemetry settings on enabled.
TODO: Requires Fixing

2021-09-12 15:36 UTC, jonathanyeung commented on packages/common-server/src/server.ts
> +      //TODO: double check that this will convert properly.
TODO: Requires Check

2021-09-14 00:40 UTC, kevinslin requested changes
lgtm, minor comment about getting release version. 

1. can you update the [[Telemetry|dendron.ref.telemetry]] docs?
2. is there a reason this is still a draft?
3.  for future changes like this, can you break this apart into multiple iterations?
    1) make sure the thing works (eg. sentry error reporting, we can catch for one error)
    2) add exception handling everywhere
4. rebase from master to resolve conflicts

2021-09-14 00:40 UTC, kevinslin commented on .github/workflows/create-vsix-artifact.yml
> +          echo "DENDRON_RELEASE_VERSION=`cat ./packages/plugin-core/package.json | jq ".version" -r | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}'`" >
heads up that as part of the build process we generate a `meta.json` file in `packages/plugin-core` that looks like the following. you can use this to get the release version

```json
{"@dendronhq/api-server":"0.58.3","@dendronhq/common-all":"0.58.3","@dendronhq/common-frontend":"0.58.3","@dendronhq/common-server":"0.58.3","@dendronhq/common-test-utils":"0.58.3","@dendronhq/dendron-11ty":"1.58.3","@dendronhq/dendron-cli":"0.58.3","dendron-design-system":"0.1.0","@dendronhq/dendron-next-server":"0.58.3","@dendronhq/engine-server":"0.58.3","@dendronhq/engine-test-utils":"0.58.3","generator-dendron":"0.1.0","@dendronhq/lsp-client-uber":"0.28.7-alpha.0","@dendronhq/lsp-server":"0.28.7-alpha.0","@dendronhq/plugin-core":"0.58.3","@dendronhq/pods-core":"0.58.3"}
```

2021-09-14 10:28 UTC, jonathanyeung commented
> lgtm, minor comment about getting release version.
> 
> 1. can you update the [[Telemetry|dendron.ref.telemetry]] docs?
> 2. is there a reason this is still a draft?
> 3. for future changes like this, can you break this apart into multiple iterations?
>    
>    1. make sure the thing works (eg. sentry error reporting, we can catch for one error)
>    2. add exception handling everywhere
> 4. rebase from master to resolve conflicts

Thanks for reviewing!

1. Updated the PR (https://github.com/dendronhq/dendron-site/pull/194) to include additional changes to the main telemetry page.
2. I had to do some additional testing on the .vsix first.  Moving out of draft mode now
3. Sounds good - iterate!
4. Done

2021-09-14 17:16 UTC, kevinslin approved these changes

2021-09-14 17:19 UTC, merged