feat(publish): mobile navigation
dendronhq/dendron pull request #1407
Opened 2021-09-24 12:11 UTC by viztor

a working, albeit not as ideal implementation of mobile nav simulating existing 11ty template without changing much of the laylout.

2021-09-24 18:02 UTC, kevinslin requested changes
awesome new design! one issue I found at certain screen size is that the hamburger button doesn't make it to the header. see https://www.loom.com/share/99daa50bedf54123ab8e9333c70cd812

2021-09-24 20:02 UTC, viztor commented
> awesome new design! one issue I found at certain screen size is that the hamburger button doesn't make it to the header. see https://www.loom.com/share/99daa50bedf54123ab8e9333c70cd812

I did some last minute fix without realizing the side effect for the side bar. I'm having difficulty reproduce the hamburger issue though, can you pull and check if the issue still persist?

2021-09-24 20:38 UTC, kevinslin commented
that fixed it!

2021-09-25 01:35 UTC, kevinslin approved these changes

2021-09-25 01:35 UTC, merged