chore: fix expect.toContain to actually assert
dendronhq/dendron pull request #1690
Opened 2021-11-10 09:32 UTC by nickolay-kondratyev

# Pull Request Checklist

expect.toContain() used to not actually assert anything prior to this change. 

## General

### Quality Assurance
- [ ] add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [x] make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [ ] do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [ ] after you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
  - NOTE: if you running MacOS or Linux, pay special attention to the Windows output and vice versa if you are developing on Windows

2021-11-10 13:11 UTC, hikchoi requested changes
Thanks for the catch. Left a minor request on the fixed MoveHeader tests

2021-11-10 13:11 UTC, hikchoi commented on packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts
> +              // );
My intention here was to assert that the expected error was being thrown. 

Can we also`expect(error.message).toEqual(cmd.headerNotSelectedError.message);`?

probably safe to remove the comments here as well.

2021-11-11 03:24 UTC, hikchoi commented on packages/plugin-core/src/test/suite-integ/MoveHeader.test.ts
> +              // );
Ah, ok. I'll take a look

2021-11-11 05:14 UTC, jonathanyeung approved these changes

2021-11-16 22:53 UTC, kevinslin approved these changes

2021-11-16 22:53 UTC, merged