fix: disappearing vaults in vault selection quickpick
dendronhq/dendron pull request #1717
Opened 2021-11-15 17:21 UTC by hikchoi

# fix: disappearing vaults in vault selection quickpick
This PR:
- Fixes a bug where vaults disappear intermittently
- Clean up a minor error in `MoveNoteCommand`

bug:
- There was a bug where one vault would be in the suggested vault in the vault selection quickpick but when we ran the command again, it disappeared.
- What actually happened is that:
1. The first quickpick also had a missing vault. 
2. This vault and the vault that disappeared on the second execution had the same `fsPath`, which the vault suggestion logic was using to sort the vaults before suggesting. (Had to watch the loom recording a million times to catch this :sweat_smile: )
3. After the sort, the vault suggestion util would go through the already suggested vaults and remaining vaults to add the outstanding vault suggestions. 
4. Here, one of the two vaults with the same `fsPath` was not being added (the one that came after) to the suggestion because the the util was only looking at the `fsPath` when in fact just the `fsPath` was not enough to guarantee that two vaults are the same vault. 
5. Since the sort function didn't guarantee the sort order for the two vaults, it looked like the vault was disappearing if it came after the other one.

the vault suggestion util is now fixed to filter out the already suggested vaults before dumping the outstanding vaults to the suggestion to avoid comparing by `fsPath` altogether.

# Pull Request Checklist

You can go to [dendron pull requests](https://wiki.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html) to see full details for items in this checklist.

## General

### Quality Assurance
- [ ] Add a [test](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#writing-tests) for the new feature
- [ ] Make sure all the existing [tests](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#running-all-tests) pass
- [ ] Do a spot check by running your feature with our [test workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace)
- [ ] If your tests involve running [[manual Testing|dendron://dendron.dendron-site/dendron.dev.qa.test#manual-testing]], make sure to update [[Test Workspace|dendron://dendron.dendron-site/dendron.dev.ref.test-workspace]] with any necessary notes/additions to perform manual test ^9jtWc6ov340p
- [ ] After you submit your pull request, check the output of our [integration test](https://github.com/dendronhq/dendron/actions) and make sure all tests pass
  - NOTE: If you running MacOS or Linux, pay special attention to the Windows output and vice versa if you are developing on Windows

#### Special Cases
- [ ] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#updating-test-snapshots)
- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in [test-workspace](https://wiki.dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#test-workspace). We use this to manually inspect new changes and for auto regression testing 

### Docs
- [ ] Make sure that the PR title follows our [commit style](https://wiki.dendron.so/notes/adc39825-77a6-46cf-9c49-2642fcb4248e.html#commit-style)
- [ ] Please summarize the feature or impact in 1-2 lines in the PR description
- [ ] If your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR

Example PR Description
```markdown
# feat: capitalize all foos

This changes capitalizes all occurrences of `foo` to `Foo` 

Docs PR: <URL_TO_DOCS_PR>
```

## Special Cases

### First Time PR
- [ ] Sign the [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) which will be prompted by our github bot after you submit the PR
- [ ] Add your [discord](https://discord.gg/AE3NRw9) alias in the review so that we can give you the [horticulturalist](https://wiki.dendron.so/notes/7c00d606-7b75-4d28-b563-d75f33f8e0d7.html#horticulturalist) badge in our community

### Git
- [ ] Make sure your branch names adhere to our commit style [[#^6zdCscSXs1MM]]
    - All PRs should start with `[feat|fix|enhance|]/[{description-of-pr-in-kebab-case}]`
        - `eg. feat/add-thisthing`

### Analytics
- [ ] If you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### Github Issue
- [ ] If this pull request is addressing an existing issue, make sure to link this PR to the issue that it is resolving.
- [ ] If the resolution comes with a document update, link the docs PR to the issue as well.

2021-11-15 17:23 UTC, hikchoi commented
pinging @jonathanyeung to make sure this all looks good.

2021-11-16 02:01 UTC, kevinslin requested changes
nice diagnosis! can you add a test for this?

2021-11-16 15:27 UTC, hikchoi commented
> nice diagnosis! can you add a test for this?

done :)

2021-11-16 23:03 UTC, kevinslin approved these changes

2021-11-16 23:03 UTC, merged