fix: decorations working for long notes, improved task note decorations
dendronhq/dendron pull request #1725
Opened 2021-11-17 08:36 UTC by SeriousBug

- Thanks to an optimization, all decorations (like link highlighting) are now displayed even in very long notes.
- Task note decorations are colored with the same color as the link to make them easier to distinguish from regular text.
- Task notes say `priority:` instead of `prio:` for priorities.

![](https://i.imgur.com/rhCykfd.png)

2021-11-18 16:55 UTC, kevinslin requested changes
Found an edge case where if I start from a task note and then go to a note that links to it, the decorators show up 2x: https://www.loom.com/share/f04e23bb082642f98221aa912ffba1d2?from_recorder=1&focus_title=1

Repro by going to [[Prepare Report|task.2021.10.26.020813.prepare-report]] in test-workspace

2021-11-18 16:55 UTC, kevinslin commented on packages/common-all/src/types/workspace.ts
>    maxNoteDecoratedLength?: number;
if we're no longer using, does it make sense to just remove altogether?

2021-11-18 16:55 UTC, kevinslin commented on packages/plugin-core/src/features/windowDecorations.ts
> +            ...warnBadFrontmatterContents(activeEditor.document, frontmatter)
can we rename this method? `warnBadFrontmatterContents` makes me think that is bad frontmatter. `checkAndWarnIfBadFrontmatterContents` would be more descriptive

2021-11-19 07:47 UTC, SeriousBug commented
> Found an edge case

Oops! Thought I had fixed this with the `mergeRanges` function but looks like I used it in the wrong order :)

Fixed the bug and applied other feedback now.

2021-11-19 15:59 UTC, kevinslin approved these changes

2021-11-19 15:59 UTC, merged