fix: Publishing dev server keeps running after exiting on Windows
dendronhq/dendron pull request #2035
Opened 2022-01-03 08:58 UTC by SeriousBug

Fixes an issue where on Windows, the next server would continue running even after the Dendron CLI is interrupted with Ctrl+C.

I believe this change will cause a terminal window to appear when using the publish dev plugin command, but I was unfortunately unable to test that. This is necessary because it appears that Windows otherwise doesn't let applications handle an interrupt, so node/execa can't stop the server when Dendron exits.

2022-01-03 17:57 UTC, kevinslin requested changes

2022-01-03 17:57 UTC, kevinslin commented on packages/pods-core/src/builtin/NextjsExportPod.ts
> +    const out = $$(cmdDev, { cwd: nextPath, windowsHide: false });
can we explicitly pass this in as an option from the plugin?

2022-01-05 16:42 UTC, kevinslin commented
looks like there's a compiler error

2022-01-06 10:35 UTC, SeriousBug commented
Works now!

2022-01-06 21:15 UTC, SeriousBug commented
The failing windows plugin tests work fine locally.

2022-01-07 04:12 UTC, kevinslin approved these changes

2022-01-07 04:12 UTC, merged