chore: import note metadata on markdown import
dendronhq/dendron pull request #2195
Opened 2022-01-18 09:46 UTC by Harshita-mindfire

# Pull Request Checklist

If this is your first time submitting a pull request to Dendron, copy and paste the full [Dendron Review Checklist](https://docs.dendron.so/notes/1EoNIXzgmhgagqcAo9nDn.html) into this request and check off each item as necessary. 

This template contains the short checklist which is used by the Dendron core team. 

## Testing
- [ ] [Write Tests](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#writing-tests) 
- [ ] [Confirm existing tests pass](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#executing-tests)
- [ ] [Confirm manual testing](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#manual-testing) 
- [ ] If your tests changes an existing snapshot, make sure that snapshots are [updated](https://docs.dendron.so/notes/99q7A73uGmCwu2KvSHZro.html#updating-test-snapshots)
- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), make sure that it is included in the [test workspace](https://docs.dendron.so/notes/dtMsF12SF2SUhLN10sYe2.html)
### Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
### Analytics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://docs.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

2022-01-19 06:03 UTC, jonathanyeung requested changes

2022-01-19 06:03 UTC, jonathanyeung commented on packages/pods-core/src/builtin/MarkdownPod.ts
> +          description: "metadata key mappings to use incase of conflicts",
Should we amend this description a bit: 

"An optional set of variable mappings, with the key being the variable name in the import source and the value being the resulting variable name in Dendron. See http://wiki.dendron.so/asdf for examples."

And then, shall we add the corresponding `http://wiki.dendron.so/asdf` page? :)

2022-01-19 06:03 UTC, jonathanyeung commented on packages/pods-core/src/builtin/MarkdownPod.ts
> +   * config. If not provided, concatinates '_imported' in imported FM keys.
nit: `concatenates`

2022-01-20 09:50 UTC, Harshita-mindfire commented on packages/pods-core/src/builtin/MarkdownPod.ts
> +          // append _imported in imported metadata keys
Yes, would be better if we have something similar to `onExportComplete` for import v2 to provide feedback of import. Presently I updated the description of the `importFrontmatter` property. Let me know if this makes sense for now.

2022-01-20 18:01 UTC, kevinslin approved these changes

2022-01-21 05:40 UTC, merged