fix: recognise case sensitive asset reference
dendronhq/dendron pull request #2350
Opened 2022-02-03 12:21 UTC by Harshita-mindfire

Fix for https://github.com/dendronhq/dendron/issues/1237

2022-02-03 16:29 UTC, kevinslin requested changes
can you make sure the github pr follows our commit style message? we should be able to copy the title of the message and add it to the changelog

[[Commit Style|dendron://dendron.docs/dev.process.review#commit-style]]

2022-02-03 16:29 UTC, kevinslin commented on packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts
> +        console.log("wsRoot", wsRoot);
remove console.log

2022-02-03 19:17 UTC, SeriousBug requested changes
I have one concern about case-sensitive OSs. Could you explain a bit why we need to lowercase the file path? What was the problem in the referenced issue? How does lowercasing it fix that?

2022-02-03 19:17 UTC, SeriousBug commented on packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts
> +          .replace(/[\\]/g, "/");
nitpick: `path.posix.join` will always use unix style joins instead if that's the intention. Or just type `assets/image.JPEG` directly :)

2022-02-03 19:17 UTC, SeriousBug commented on packages/pods-core/src/builtin/MarkdownPod.ts
> +    return path.toLowerCase().replace(/[\\|/.]/g, "");
Won't this cause problems on case sensitive OSs like Linux/Mac? I think we should preserve the case of the file paths

2022-02-04 07:47 UTC, SeriousBug commented on packages/engine-test-utils/src/__tests__/pods-core/MarkdownPod.spec.ts
> +        expect(fileBody3Content).toContain(`[image](/${imagePath})`);
This test doesn't seem to test the linked issue. In the linked issue, the markdown file contains a link where the asset is in the same directory as the note, and the link looks like `![](image.jpg)`. The link is relative from the note file itself and not the root folder we're importing from.

2022-02-04 08:06 UTC, SeriousBug approved these changes
After talking to Harshita I see how this PR fixes the issue. Looks good to me.

2022-02-04 17:22 UTC, kevinslin approved these changes

2022-02-04 17:42 UTC, kevinslin commented
Looks good. can you update the github issue link so it doesn't autoclose? see updated SOP on that in https://github.com/dendronhq/dendron-docs/commit/683f8a4c7f5fc16dda6429e40c0fb4efc4881e8e

afterwards, feel free to add to release notes according to [[Ready to Ship|dendron://private/area.product.sop.ready-to-ship]]. note the changes in https://github.com/dendronhq/org-private/commit/1f69fa963d1c3aa29132078e3330166e38cbf410

2022-02-07 17:21 UTC, merged