fix(workspace): fix crash in updated fm field logic on doc save
dendronhq/dendron pull request #2535
Opened 2022-03-08 08:25 UTC by jonathanyeung

## fix(workspace): fix crash in updated fm field logic on doc save

One of the top Sentry hitters right now is in `onWillSaveNote`, "Cannot read property 'updated' of undefined".

This happens when we can't find a particular note in the engine when it's being saved.  I think this is caused by a race condition between the vscode `onWillSaveNote` callback and our filewatcher logic of adding the note to the engine for the cases of a user adding a new note outside of the Lookup command.

We should just avoid modifying the `updated` property if we can't find it - according to VSCode's API docs, if your  `onWillSaveNote` logic crashes 3 times, it will no longer get invoked.

---

# Dendron Extended PR Checklist

- NOTE: the links don't work. you'll need to go into the wiki and use lookup to find the note until we fix some issues in the markdown export

## Code

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [x] sticking to existing conventions instead of creating new ones
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended
- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [N/A] check if this change adversely impact performance
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [N/A] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Instrumentation

### Basics
- [N/A] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### Extended
- [x] can we track the performance of this change to know if it is _successful_?
  - via Sentry Data

## Tests

### Basics

- [ ] [Write Tests](dev.process.qa.test) 
- [ ] [Confirm existing tests pass](dev.process.qa.test)
- [ ] [Confirm manual testing](dev.process.qa.test) 
- [ ] Common cases tested
- [ ] 1-2 Edge cases tested
- [ ] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

## Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
- [ ] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## Close the Loop

### Extended
- [ ]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

2022-03-08 23:28 UTC, kevinslin commented on packages/plugin-core/src/WorkspaceWatcher.ts
> +    // If we can't find the note, don't do anything
do we need to log this? when does this happen?

2022-03-09 19:02 UTC, SeriousBug requested changes
Looks good, just one comment.

2022-03-10 04:49 UTC, jonathanyeung commented on packages/plugin-core/src/WorkspaceWatcher.ts
>      }) as NoteProps;
Good call - actually I was just looking at some of the Sentry data, and it looks like a lot of our issues occur around places where we do a `as NoteProps` cast - we should get rid of them in most scenarios and assume that the note may not always be found.

2022-03-10 21:39 UTC, kevinslin commented
pr looks good though looks like there's a build error now

2022-03-11 02:49 UTC, jonathanyeung commented
> pr looks good though looks like there's a build error now

fixed now

2022-03-12 00:01 UTC, merged