chore: mark `dendron.dendron-markdown-links` as incompatible
dendronhq/dendron pull request #2853
Opened 2022-04-29 05:36 UTC by SeriousBug

The extension `dendron.dendron-markdown-links` is both unnecessary since the note graph is built into Dendron now, but it also breaks the built-in note graph. This change will warn users if they have the extension installed.

2022-04-29 11:01 UTC, jonathanyeung approved these changes

2022-04-29 11:02 UTC, jonathanyeung commented
Looks like there's a failing test: 

```log
@dendronhq/plugin-core:   2) FIND_INCOMPATIBLE_EXTENSIONS
@dendronhq/plugin-core: 	at process.topLevelDomainCallback (node:domain:152:15)
@dendronhq/plugin-core:        GIVEN findIncompatibleExtensions selected
@dendronhq/plugin-core: 	at process.callbackTrampoline (node:internal/async_hooks:128:24)
@dendronhq/plugin-core:          THEN List all as not installed if found none:
@dendronhq/plugin-core:       AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
@dendronhq/plugin-core: 11 !== 10
```

2022-04-29 11:03 UTC, jonathanyeung requested changes
looks like 1 failing test that expects the exact # of incompatible extensions.  Maybe worth removing that test? (or that check)

2022-05-03 01:57 UTC, hikchoi requested changes
```expect(out.installStatus.length).toEqual(10);``` from both tests could be removed.

Also, the doctor command links to a document with a full list and detail about incompatible extensions: `[[Incompatible Extensions|dendron://dendron.dendron-site/dendron.guides.troubleshooting.incompatible-extensions]]`

New additions should be added.

2022-05-03 05:33 UTC, SeriousBug commented
Thanks for catching the error in the tests!

@hikchoi I added this extension to that list already, but yes we should add any others we know cause bugs.

2022-05-03 05:49 UTC, hikchoi commented
> Thanks for catching the error in the tests!
> 
> @hikchoi I added this extension to that list already, but yes we should add any others we know cause bugs.

ah right. I didn't notice the update to the docs because a docs PR wasn't linked to this 😅

2022-05-03 23:17 UTC, kevinslin approved these changes

2022-05-03 23:17 UTC, merged