feat(publish): Custom theme support
dendronhq/dendron pull request #2887
Opened 2022-05-06 09:03 UTC by SeriousBug

Docs: https://github.com/dendronhq/dendron-site/pull/492

2022-05-10 07:34 UTC, jonathanyeung requested changes
Were we planning on alpha testing this first with a limited population?  If not, do we want to use the FeatureToaster and TipOfDay to let people know that this option exists?

2022-05-10 17:41 UTC, kevinslin commented on packages/common-all/src/constants/index.ts
> +  CUSTOM_THEME_CSS: "custom.css",
we can amoeba it - start off by having the same file and splitting it off if users want that

2022-05-10 17:59 UTC, kevinslin requested changes
- left some doc comments > https://github.com/dendronhq/dendron-site/pull/492#pullrequestreview-968189217
- can you also confirm that dark theme works?

2022-05-10 20:32 UTC, SeriousBug commented
> @kevinslin can you also confirm that dark theme works?

It doesn't actually, the navigation bar shows up in a light theme, which is why I didn't highlight the dark theme support in the docs. I was thinking of solving that in a next iteration so the custom theme support can go out now, should I fix that in this PR instead?

2022-05-10 21:26 UTC, kevinslin commented
> It doesn't actually, the navigation bar shows up in a light theme, which is why I didn't highlight the dark theme support in the docs. I was thinking of solving that in a next iteration so the custom theme support can go out now, should I fix that in this PR instead?

ah, nice. would leave it as is then

>     @jonathanyeung alpha testing this first with a limited population

lets do this when we add it add the preview css feature changes

2022-05-10 23:40 UTC, kevinslin approved these changes

2022-05-11 01:58 UTC, jonathanyeung commented on packages/common-all/src/constants/index.ts
> +  CUSTOM_THEME_CSS: "custom.css",
One concern though is that it's harder to rename this file once users have one.  We'd have to do a migration or ask them to do it.

2022-05-11 01:59 UTC, jonathanyeung commented
Re: rollout plan, sounds good! - by 'alpha' testing I didn't mean specifically limiting its audience, I was more referring to the treatment of it as a 'germ' stage feature.

2022-05-11 05:26 UTC, SeriousBug commented
@jonathanyeung Ah my bad, I must have misunderstood you then. It is an alpha feature, I think the documentation gets this across pretty well. The main thing that makes it alpha is the selectors for which we have no guarantee will be stable.

For the file, I think one way to handle it would be to have this file apply to both preview and publishing. One way to think about the preview is that it's a preview of what the note will look like once it's published, in which case applying the same theme would make more sense. We would then allow overrides in the form of `custom.publish.css` and `custom.preview.css` that apply only to one, for anyone who uses a custom publishing theme but doesn't want that to apply to the preview.

2022-05-11 15:28 UTC, merged