enhance/apply temp spacing
dendronhq/dendron pull request #3094
Opened 2022-06-15 16:09 UTC by kevinslin

- add capture helper
- update

2022-06-16 03:06 UTC, jonathanyeung requested changes

2022-06-16 03:06 UTC, jonathanyeung commented on packages/common-server/src/template.ts
> +    capture: (text: string, pattern: string): string => {
Let's also modify `genTrackPayload` in this file to get data for this helper method.

2022-06-16 03:06 UTC, jonathanyeung commented on packages/engine-test-utils/src/__tests__/common-all/template.spec.ts
> +    describe("AND WHEN using capture helper", () => {
very nitpick: `AND` usually combos with the THEN (the verification clause, as in doing multiple verifications) as opposed to the WHEN.

2022-06-17 04:16 UTC, jonathanyeung commented
lgtm, but looks like there's a cli test error.

2022-06-17 16:15 UTC, kevinslin commented
> lgtm, but looks like there's a cli test error.

fixed

2022-06-20 15:45 UTC, merged