fix(workspace): proper checking on invalid data for write note ops
dendronhq/dendron pull request #3137
Opened 2022-06-23 10:48 UTC by jonathanyeung

## fix(workspace): proper checking on invalid data for write note ops

We have some improperly typed responses in API.ts that make the data prop of `Resp` be `Required`.  The server was not passing back Data in some cases due to exceptions, which led to cascading issues on the plugin side because the type definitions on the responses were not accurate.

The main way I found this manifesting itself is with Doctor Fix:Frontmatter, which was always showing a modal dialog error because we try to re-write root as part of that operation, which store doesn't permit right now (another separate issue).

Example errors that we were getting below: 

```log
"TypeError: Cannot read properties of undefined (reading 'forEach')
    at DendronEngineClient.refreshNotesV2 (/Users/jyeung/code/dendron/dendron/packages/engine-server/src/engineClient.ts:356:11)
    at DendronEngineClient.bulkWriteNotes (/Users/jyeung/code/dendron/dendron/packages/engine-server/src/engineClient.ts:230:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at BackfillService.updateNotes (/Users/jyeung/code/dendron/dendron/packages/engine-server/src/backfillV2/service.ts:43:5)
    at DoctorCommand.execute (/Users/jyeung/code/dendron/dendron/packages/plugin-core/src/commands/Doctor.ts:412:9)
    at DoctorCommand.run (/Users/jyeung/code/dendron/dendron/packages/plugin-core/src/commands/base.ts:113:14)
    at /Users/jyeung/code/dendron/dendron/packages/plugin-core/src/_extension.ts:1149:13
    at o._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:62513)"

    "TypeError: Cannot read properties of undefined (reading 'filter')
    at extractNoteChangeEntriesByType (/Users/jyeung/code/dendron/dendron/packages/common-all/lib/utils/index.js:935:20)
    at EventEmitter.<anonymous> (/Users/jyeung/code/dendron/dendron/packages/plugin-core/out/src/services/EngineAPIService.js:211:81)
    at EventEmitter.emit (node:events:402:35)
    at EventEmitter.emit (node:domain:475:12)
    at EventEmitter.fire (/Users/jyeung/code/dendron/dendron/packages/common-all/lib/types/events.js:40:23)
    at DendronEngineClient.bulkWriteNotes (/Users/jyeung/code/dendron/dendron/packages/engine-server/lib/engineClient.js:126:36)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async BackfillService.updateNotes (/Users/jyeung/code/dendron/dendron/packages/engine-server/lib/backfillV2/service.js:36:9)
    at async DoctorCommand.execute (/Users/jyeung/code/dendron/dendron/packages/plugin-core/out/src/commands/Doctor.js:269:17)
    at async DoctorCommand.run (/Users/jyeung/code/dendron/dendron/packages/plugin-core/out/src/commands/base.js:69:20)
    at async /Users/jyeung/code/dendron/dendron/packages/plugin-core/out/src/_extension.js:892:17
    at async o._executeContributedCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:62513)"
```

---

## Code

### Basics

- [ ] code should follow [Code Conventions](dev.process.code)
- [ ] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [ ] sticking to existing conventions instead of creating new ones
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended
- General
  - [ ] check whether code be simplified
  - [ ] check if similar function already exist in the codebase. if so, can it be re-used?
  - [ ] check if this change adversely impact performance
- Operations
  - [ ] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [ ] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Instrumentation

### Basics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### Extended
- [ ] can we track the performance of this change to know if it is _successful_?
  - eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-855715612)

## Tests

### Basics

- [ ] [Write Tests](dev.process.qa.test) 
- [ ] [Confirm existing tests pass](dev.process.qa.test)
- [ ] [Confirm manual testing](dev.process.qa.test) 
- [ ] Common cases tested
- [ ] 1-2 Edge cases tested
- [ ] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

### Extended
- [ ] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the [test workspace](dev.ref.test-workspace)
- CSS
  - [ ] display is correct for following dimensions
    - [ ] sm: screen ≥ 576px, eg. iphonex, (375x812)
    - [ ] lg: screen ≥ 992px
    - [ ] xxl: screen ≥ 1600px eg. mac (1600x900)
  - [ ] display is correct for following browsers (across the various dimensions)
    - [ ] safari
    - [ ] firefox
    - [ ] chrome

## Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
- [ ] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## Close the Loop

### Extended
- [ ]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

2022-06-24 11:00 UTC, bpathakota requested changes
Think it would be better if we followed a standardized approach for fix commits - to just highlight what issue is being fixed. e.g. fix(workspace): invalid data for write note ops

2022-06-27 09:19 UTC, jonathanyeung commented
> Think it would be better if we followed a standardized approach for fix commits - to just highlight what issue is being fixed. e.g. fix(workspace): invalid data for write note ops

Reworded slightly - the fix isn't making the invalid data valid, but making sure that we can properly handle invalid data.

2022-06-27 15:26 UTC, kevinslin approved these changes

2022-06-30 10:55 UTC, bpathakota approved these changes
commit message makes sense

2022-07-06 02:45 UTC, merged