fix(workspace): properly handle error caused during duplicate note id detection
dendronhq/dendron pull request #3155
Opened 2022-06-27 11:18 UTC by hikchoi

# fix(workspace): properly handle error caused during duplicate note id detection

This PR:
- Handles the case where duplicate note id detection is triggered for a file that is opened in the editor, but is already removed (VSCode keeps the editor open even after a file system delete).
- This also covers some cases where the note is temporarily removed from the file system during workspace sync (caused by git stashing)
- Adds a custom type guard `isRespV3SuccessResp` for `RespV3` that can be used to help typescript properly narrow the type of the response.
- change `file2Note` to return a `RespV3` in cases where the file path does not exist.
- refactors all usage of `file2Note`.

## Code

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [x] sticking to existing conventions instead of creating new ones
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended
- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [x] check if this change adversely impact performance
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [x] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Instrumentation

### Basics
- [~] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### Extended
- [~] can we track the performance of this change to know if it is _successful_?
  - eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-855715612)

## Tests

### Basics

- [~] [Write Tests](dev.process.qa.test) 
- [x] [Confirm existing tests pass](dev.process.qa.test)
- [x] [Confirm manual testing](dev.process.qa.test) 
- [~] Common cases tested
- [~] 1-2 Edge cases tested
- [~] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

### Extended
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the [test workspace](dev.ref.test-workspace)
- CSS
  - [~] display is correct for following dimensions
    - [~] sm: screen ≥ 576px, eg. iphonex, (375x812)
    - [~] lg: screen ≥ 992px
    - [~] xxl: screen ≥ 1600px eg. mac (1600x900)
  - [~] display is correct for following browsers (across the various dimensions)
    - [~] safari
    - [~] firefox
    - [~] chrome

## Docs
- [~] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
- [x] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## Close the Loop

### Extended
- [~]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

2022-06-27 11:20 UTC, hikchoi commented
@tma66 adding you as a reviewer as this touches the store logic a bit.

2022-06-27 15:24 UTC, kevinslin approved these changes

2022-06-29 14:27 UTC, kevinslin commented
looks like theres now some conflicts from master

2022-06-30 10:20 UTC, bpathakota requested changes
To be consistent, fixes should mainly highlight the issue in the commit messages. e.g. fix(workspace): duplicate note id detected even after a file is removed

2022-06-30 17:47 UTC, hikchoi commented
> To be consistent, fixes should mainly highlight the issue in the commit messages. e.g. fix(workspace): duplicate note id detected even after a file is removed

that makes sense. thanks

2022-06-30 17:49 UTC, merged