fix(workspace): workspace sync will maintain proper engine state
dendronhq/dendron pull request #3233
Opened 2022-07-13 07:06 UTC by jonathanyeung

## fix(workspace): workspace sync will maintain proper engine state

This change fixes an issue where notes added by workspace sync were causing engine state drift.  The root cause is that the `updateNote` API doesn't return `NoteChangedEvents[]`, and we were using `updateNote` instead of `writeNote` in the file watcher `onCreate` callback.

This change adds a full `NoteChangedEvents[]` in the updateNote response.  I've intentionally not added tests for this, since we will likely modify this API surface as part of @tma66's refactoring work.

---

## Code

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [x] sticking to existing conventions instead of creating new ones
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended
- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [x] check if this change adversely impact performance
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [x] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Tests

### Basics

- [ ] [Write Tests](dev.process.qa.test) 
- [ ] [Confirm existing tests pass](dev.process.qa.test)
- [ ] [Confirm manual testing](dev.process.qa.test) 
- [ ] Common cases tested
- [ ] 1-2 Edge cases tested
- [ ] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

## Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
- [ ] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

2022-07-13 10:19 UTC, hikchoi requested changes
One small comment, but otherwise looks good.

2022-07-14 02:31 UTC, tma66 commented on packages/engine-server/src/drivers/file/storev2.ts
>      }
We should also push entry for "update" if its not a newNode.

2022-07-14 02:37 UTC, tma66 commented on packages/plugin-core/src/services/TextDocumentService.ts
> +    const resp = await engine.updateNote(props);
It might be simpler to just return props if there is no resp.error.

2022-07-14 07:50 UTC, jonathanyeung commented on packages/engine-server/src/drivers/file/storev2.ts
> +    return { data: changes, error: null };
Maybe I'm misunderstanding your question, but it's necessary in order to match the updated interface definition.  I've wrapped in a try catch block to propagate an error if it should occur.

2022-07-14 13:49 UTC, kevinslin approved these changes

2022-07-14 15:55 UTC, merged