enhance(nextjs-template): use note's `desc` for SEO description
dendronhq/dendron pull request #3261
Opened 2022-07-18 11:17 UTC by namjul

docs: [[seo description should be generated from `desc` field of note if available|task.2022.07.17.seo-description-should-be-generated-from-desc-field-of-note-if-available]]

# Pull Request Checklist

If you are a community contributor, copy and paste the PR template from [Dendron Community PR Checklist](https://gist.github.com/kevinslin/5d1a6663638259e7dbd33b01975cc00f) and add it to the body of the pull request. 

If you are a team member, copy and paste the template from [Dendron Extended PR Checklist](https://gist.github.com/kevinslin/dfc7a101f21c58478216aa0d70256bc2).

To copy the template, click on the `Raw` button on the gist to copy the plaintext version of the template to this PR.

2022-07-19 13:12 UTC, namjul commented on packages/common-all/src/utils/publishUtils.ts
> +      description: desc || excerpt || undefined,
[`299cbb9` (#3261)](https://github.com/dendronhq/dendron/pull/3261/commits/299cbb9754f912bec2033c86143e7ec11445a5c7)

2022-07-19 16:59 UTC, kevinslin approved these changes

2022-07-19 17:05 UTC, bpathakota requested changes
Would update this to `enhance(publish): use note's desc for SEO description`. For PR titles, these are the [[Steps|dendron://dendron.handbook/area.product.sop.ready-to-ship#steps]] to follow. Let me know if I can clarify anything!

2022-07-19 21:21 UTC, namjul commented
> Would update this to `enhance(publish): use note's desc for SEO description`. For PR titles, these are the [[Steps|dendron://dendron.handbook/area.product.sop.ready-to-ship#steps]] to follow. Let me know if I can clarify anything!

Thank you Bindhu. I updated the PR title and used rebase to change the commit messages.

2022-07-20 13:04 UTC, bpathakota commented
@namjul The PR should still have the categorization of the PR (e.g. feat/enhance/fix) and based the [[Product Scope|dendron://dendron.dendron-site/dendron.ref.scopes]] chosen should be in parenthesis. e.g. `enhance(publish): use note's desc for SEO description`, similar to this PR - https://github.com/dendronhq/dendron/pull/3237

2022-07-20 15:42 UTC, merged