enhance/remove show preview
dendronhq/dendron pull request #3276
Opened 2022-07-20 15:31 UTC by kevinslin

- remove show preview
- remove show preview command

2022-07-25 18:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dendronhq/dendron?pullRequest=3276) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dendronhq/dendron?pullRequest=3276) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dendronhq/dendron?pullRequest=3276) it.</sub>

2022-07-26 02:31 UTC, jonathanyeung requested changes

2022-07-26 02:31 UTC, jonathanyeung commented on packages/plugin-core/package.json
> +        "windows": "ctrl+k v",
How did we come up with this keybinding? It's very different between mac and windows

2022-07-26 03:10 UTC, kevins8 commented
This is the default windows keybinding for vscode preview. the mac one
should actually also be this, didn't want to change it in case people
already had it set.
the reason we can do it for windows is because users can't actually press
windows+p without triggering the menu

On Mon, Jul 25, 2022 at 7:31 PM jonathanyeung ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In packages/plugin-core/package.json
> <https://github.com/dendronhq/dendron/pull/3276#discussion_r929469749>:
>
> > @@ -1301,7 +1292,7 @@
>        },
>        {
>          "command": "dendron.togglePreview",
> -        "windows": "windows+ctrl+p",
> +        "windows": "ctrl+k v",
>
> How did we come up with this keybinding? It's very different between mac
> and windows
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dendronhq/dendron/pull/3276#pullrequestreview-1050292885>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABPIPXRJ63EJ26V5OJ4YYLVV5EXRANCNFSM54ED733Q>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-07-27 15:25 UTC, merged