chore(workspace): validate filename that are illegal in SQLite
dendronhq/dendron pull request #3484
Opened 2022-09-02 12:35 UTC by hikchoi

# chore(workspace): validate filename that are illegal in SQLite

This PR:
- Extends the file name validation logic to capture illegal SQLite characters.
- Enhance warning / error messages to be more specific about what is invalid.
- Add doctor action `fixInvalidFileNames` on cli and extension
- 

# Pull Request Checklist
## Code

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [x] sticking to existing conventions instead of creating new ones
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended
- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [x] check if this change adversely impact performance
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [x] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Instrumentation

### Basics
- [x] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### Extended
- [x] can we track the performance of this change to know if it is _successful_?
  - eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-855715612)

## Tests

### Basics

- [x] [Write Tests](dev.process.qa.test) 
- [x] [Confirm existing tests pass](dev.process.qa.test)
- [x] [Confirm manual testing](dev.process.qa.test) 
- [x] Common cases tested
- [x] 1-2 Edge cases tested
- [x] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

### Extended
- [~] If you are adding a new language feature (graphically visible in VS Code/preview/publishing), an example is included in the [test workspace](dev.ref.test-workspace)
- CSS
  - [~] display is correct for following dimensions
    - [~] sm: screen ≥ 576px, eg. iphonex, (375x812)
    - [~] lg: screen ≥ 992px
    - [~] xxl: screen ≥ 1600px eg. mac (1600x900)
  - [~] display is correct for following browsers (across the various dimensions)
    - [~] safari
    - [~] firefox
    - [~] chrome

## Docs
- [x] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
- [~] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## Close the Loop

### Extended
- [~]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

2022-09-06 13:15 UTC, hikchoi commented
docs: https://github.com/dendronhq/dendron-site/pull/639

2022-09-06 18:11 UTC, kevinslin requested changes

2022-09-06 18:11 UTC, kevinslin commented on packages/engine-server/src/doctor/service.ts
> +          console.log("Found invalid filename in notes:\n");
ideally, we wouldn't be using `console.log` here but the [print](https://github.com/dendronhq/dendron/blob/master/packages/dendron-cli/src/commands/base.ts#L255:L255) function from the `CLICommand`. can we pass it in as an optional parameter in the constructor? by default, its a no-op.

2022-09-06 18:11 UTC, kevinslin commented on packages/engine-server/src/doctor/service.ts
> +            console.log(`  Can be automatically fixed to "${cleanedFname}"`);
extra space

2022-09-06 18:11 UTC, kevinslin commented on packages/engine-server/src/doctor/service.ts
> +          console.log("Found invalid filename in notes:\n");
also apply to other `console.log` statements

2022-09-06 18:11 UTC, kevinslin commented on packages/plugin-core/src/commands/Doctor.ts
> +      ...out.extra,
we should pick what properties we are adding but not extract everything from an `any` parameter

2022-09-07 01:23 UTC, jonathanyeung approved these changes
lgtm apart from existing comments.

2022-09-07 01:57 UTC, hikchoi commented on packages/engine-server/src/doctor/service.ts
> +            console.log(`  Can be automatically fixed to "${cleanedFname}"`);
it's an intentional indentation

2022-09-07 15:23 UTC, kevinslin approved these changes

2022-09-08 00:56 UTC, merged