chore: ab test for video in launch tutorial welcome screen
dendronhq/dendron pull request #3528
Opened 2022-09-14 19:52 UTC by Harshita-mindfire

This PR aims to add an AB test for 1 min feature highlights video in the Welcome screen displayed after running `Launch Tutorial` command. 

- used `webm` format for video, with `.mp4` there was no sound.

# Dendron Extended PR Checklist

## Code

### Basics

- [x] code should follow [Code Conventions](dev.process.code)
- [x] circular dependency check: make sure your code is not introducing new circular dependencies in plugin-core.  See [Avoiding Circular Dependencies](dev.process.code.best-practices).
- [x] sticking to existing conventions instead of creating new ones
  - eg: [if configuration for utilities are already in one module or package, add future utilities there as well](https://github.com/dendronhq/dendron/pull/1960#discussion_r786228021)

### Extended
- General
  - [x] check whether code be simplified
  - [x] check if similar function already exist in the codebase. if so, can it be re-used?
  - [x] check if this change adversely impact performance
- Operations
  - [x] when shipping this change, will it just work or will it introduce additional operational overhead due to complicated interface or known bugs?
- Architecture
  - [x] check if code is introducing changes on a foundational class or interface. if so, call for design review if needed
    - eg: [making changes to DNode](https://github.com/dendronhq/dendron/pull/2158#pullrequestreview-854689586)

## Instrumentation

### Basics
- [ ] if you are adding analytics related changes, make sure the [Telemetry](https://wiki.dendron.so/notes/84df871b-9442-42fd-b4c3-0024e35b5f3c.html) docs are updated

### Extended
- [~] can we track the performance of this change to know if it is _successful_?
  - eg: [see usage for export pod](https://github.com/dendronhq/dendron/pull/2190#pullrequestreview-855715612)

## Tests

### Basics

- [ ] [Write Tests](dev.process.qa.test) 
- [ ] [Confirm existing tests pass](dev.process.qa.test)
- [x] [Confirm manual testing](dev.process.qa.test) 
- [ ] Common cases tested
- [ ] 1-2 Edge cases tested
- [ ] If your tests changes an existing snapshot, snapshots have been [updated](dev.process.qa.test)

### Extended

## Docs
- [ ] if your change reflects documentation changes, also submit a PR to [dendron-site](https://github.com/dendronhq/dendron-site) and mention the doc PR link in your current PR
- [ ] does this change introduce a new or better way of doing things that others need to be aware of? if so, an async should be created and a process added in [Development](dev) or [Packages](pkg)

## Close the Loop

### Extended
- [~]  is this a developer BREAKING change? if another person cloning from this branch will need to adjust their dependencies or mental model of the architecture, then it is. if this is the case, make sure this is communicated according to [Close Loop](dev.process.close-loop)
  - eg: [breaking dev change due to new dependency](https://github.com/dendronhq/dendron/pull/2188#pullrequestreview-855696330)

2022-09-15 09:10 UTC, jonathanyeung commented
As discussed offline, if we can't figure out a way to embed, I'd rather us not run this experiment rather than include the file as part of our extension binary.  I think that the binary size will adversely affect download rates and it's also not going to publish to ovsx as it stands (32 mb single file size limit).  @kevinslin - thoughts?

2022-09-15 09:48 UTC, Harshita-mindfire commented
one possible workaround is uploading the video to google drive. This works fine in preview with a valid id
```html
<video preload="true" controls autoplay>
  <source
    src="https://drive.google.com/uc?export=download&amp;id=<insert-video-drive-id-here>"
    type="video/webm"
  />
</video>
```

2022-09-15 15:18 UTC, kevinslin requested changes
video doesn't seem to load or play for me > https://www.loom.com/share/7b43a4b575e9431c82b686f3cb8a7e93

2022-09-15 15:18 UTC, kevinslin commented on packages/plugin-core/assets/dendron-ws/vault/welcome_video.html
> +        src="https://org-dendron-public-assets.s3.amazonaws.com/images/dendron_feature_highlights.webm"
can we use the cloudfront link instead? will load faster > https://d2q204iup008xl.cloudfront.net/images/dendron_feature_highlights.webm

2022-09-15 15:18 UTC, kevinslin commented on packages/plugin-core/src/WelcomeUtils.ts
> +    const version = Number(vscode.version.substring(0, 4)); // version: x.xx.x
can we use the `semver` package to check for versions?

2022-09-15 15:18 UTC, kevinslin commented on packages/plugin-core/assets/dendron-ws/vault/welcome_video.html
> +        <source
can we make this take the full width of the screen?

2022-09-16 08:08 UTC, Harshita-mindfire commented
> video doesn't seem to load or play for me > 

It looks like it is still downloading. Do you have any errors in console/network?

2022-09-16 13:59 UTC, kevinslin approved these changes

2022-09-19 05:20 UTC, merged