chore(internal): remove references of deprecated methods
dendronhq/dendron pull request #3625
Opened 2022-10-03 13:38 UTC by Harshita-mindfire

This PR aims to remove references to deprecated methods in code and updates with new.

2022-10-04 07:11 UTC, hikchoi requested changes
Assuming this is not a full sweep of the deprecated methods and just partial clean-up, just commenting on the files that are changed:

In commands, instead of using the `ExtensionProvider`, can we pass in the extension through the constructor?

---

Quick list of remaining references to `getExtension`, `getDWorkspace`, and `getEngine` for whoever picks this up for a full sweep in the future: [[Remaining refs|dendron://private/user.hikchoi.reviews.3625#remaining-refs]]

2022-10-04 13:21 UTC, Harshita-mindfire commented
> Quick list of remaining references to `getExtension`, `getDWorkspace`, and `getEngine` for whoever picks this up for a full sweep in the future: [[Remaining refs|dendron://private/user.hikchoi.reviews.3625#remaining-refs]]

Thanks! using this note as a reference

2022-10-05 14:23 UTC, kevinslin approved these changes

2022-10-05 15:21 UTC, jonathanyeung approved these changes

2022-10-05 18:25 UTC, merged