fix/nextjs template breadcumbs display
dendronhq/dendron pull request #3689
Opened 2022-10-19 08:39 UTC by namjul

The aim of this PR is to fix a conflict that arises by styles coming from `.main-content` and
`antd`'s `Breadcrumb` component.

The instance of that conflict is visible in https://docs.dendron.so/notes/boiXiUPuPlk4TuwYEPiEh/ where the breadcrumb is display in a weird way in which it contains numbers.

Based on the html structure of `Breadcrumb` component in that instance it must be rendering `antd`'s `Breadcrumb` component from version [4.20.0](https://ant.design/changelog#4.20.0) or above. I am not sure how that has happened since its only accuring on the https://docs.dendron.so/ site and not on https://wiki.dendron.so/. Also the version its should render is `^4.15.5` as is defined in `packages/nextjs-template/package.json:30:1`.

Nonetheless the changes in this PR solve that possible conflict that comes about because of `.main-content` [targeting](packages/common-assets/styles/scss/content.scss:65:1)
html structure that are reflected in that new `Breadcrumb` componeont.
Moving that out of that render-tree solves this issue.

This PR further makes the following changes:
- chore: remove unused `antd` package dependency
- chore: remove unnecessary `yarn.lock` file
- chore: update yarn lock file

# Pull Request Checklist

If you are a community contributor, copy and paste the PR template from [Dendron Community PR Checklist](https://gist.github.com/kevinslin/5d1a6663638259e7dbd33b01975cc00f) and add it to the body of the pull request. 

If you are a team member, copy and paste the template from [Dendron Extended PR Checklist](https://gist.github.com/kevinslin/dfc7a101f21c58478216aa0d70256bc2).

To copy the template, click on the `Raw` button on the gist to copy the plaintext version of the template to this PR.

2022-10-19 11:44 UTC, hikchoi approved these changes

2022-10-19 17:54 UTC, kevinslin requested changes
can we also add a visual snapshot test for this?

2022-10-20 16:29 UTC, namjul commented
> can we also add a visual snapshot test for this?

[`7c527dc` (#3689)](https://github.com/dendronhq/dendron/pull/3689/commits/7c527dcec76856ec7c4f598df49c0937734fef67)

2022-10-21 02:45 UTC, kevinslin approved these changes

2022-10-21 10:21 UTC, merged