chore(internal): close video tutorial ab test
dendronhq/dendron pull request #3691
Opened 2022-10-19 12:54 UTC by Harshita-mindfire

This PR aims to close the video tutorial AB tests and makes the video default on the Welcome page.

2022-10-20 14:28 UTC, kevinslin approved these changes

2022-10-21 02:00 UTC, jonathanyeung approved these changes

2022-10-21 04:15 UTC, Harshita-mindfire commented on packages/plugin-core/src/WelcomeUtils.ts
> +export enum VideoTutorialTestGroups {
Yeah, this is used in analytics. We still have gif displayed for users below vscode version: 1.71

2022-10-21 09:32 UTC, hikchoi commented on packages/plugin-core/src/WelcomeUtils.ts
> +export enum VideoTutorialTestGroups {
Can we add a comment that this is not an enum to distinguise test groups but rather to distinguish lower vscode users?

Maybe even just change the enum name to reflect that. As long as the enum values are the same there won't be a difference in what we track.

2022-10-21 09:33 UTC, hikchoi requested changes
a small nit on the enum

2022-10-24 10:58 UTC, hikchoi approved these changes

2022-10-25 03:46 UTC, merged