[feature][plugin-core][commands] Add PasteLink Command
dendronhq/dendron pull request #512
Opened 2021-02-28 22:43 UTC by hydrosquall

# Motivation

- Reduce the effort needed to create a new note about a web resource. See #329 for more details.

# Changes

- Added the `open-graph-scraper` package + types
- Added and registered a `PasteLink` command without keyboard shortcuts (P and L are both taken, so I didn't want to overthink it). It searches the opengraph meta tags for "titles" to use in markdown
- See https://a.cl.ly/9Zu8yXgr for a demo. 

# Testing

- Not sure if testing this command is required since we just depends on a network request - should that be mocked? If not, do we need a test for just the "string building" capability?

## Development notes

<details>

<summary>(click to expand)</summary>

As this is my 1st Dendron PR, I saved notes about things I'm likely to look up someday / may be useful to other first time contributors.

- Commands to add new packages

```bash
yarn run lerna  add @types/open-graph-scraper --scope @dendronhq/plugin-core
yarn run lerna  add open-graph-scraper --scope @dendronhq/plugin-core

# Run locally - make sure to do this before running the vscode "build" command.
./bootstrap/scripts/watch.sh
```
- Where to go to run a development version of VScode. (recommend doing so with other extensions disabled for better performance): https://a.cl.ly/wbu9L7qm. Note that you can "refresh" running instances rather than closing and re-opening previous windows (see lower rectangle for where you can do this).

- I didn't have `lerna` in my global namespace, so I edited the bootstrap file to be prefixed with `yarn run`, e.g. `yarn run lerna ...` rather than bare `lerna`. 

</details

2021-02-28 22:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dendronhq/dendron?pullRequest=512) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dendronhq/dendron?pullRequest=512) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dendronhq/dendron?pullRequest=512) it.</sub>

2021-03-01 00:53 UTC, kevinslin requested changes
changes look great. can you also add a test for this?
you can use [this](https://github.com/dendronhq/dendron/blob/master/packages/plugin-core/src/test/suite-integ/CopyNoteUrl.test.ts#L39:L39) as a template.  testing instructions [here](https://dendron.so/notes/cb22bd36-d45a-4ffd-a31e-96c4b39cb7fb.html#run-a-specific-test-for-dendron-plugin)

2021-03-02 02:09 UTC, hydrosquall commented
Hi @kevins8 ,

I took at pass at writing an integration test. It feels conceptually sound to me, but I'm missing something as it doesn't run as expected (https://a.cl.ly/mXu1v6zK )

I looked at a few different options for mocking `ogs` (https://github.com/sinonjs/sinon/issues/562#issuecomment-399090111 etc didn't seem to work), making an internal layer of indirection seemed preferable to installing a 3rd party dependency just to be able to mock a default export.

2021-03-02 03:22 UTC, kevinslin approved these changes
great job. excited to get this merged :)

2021-03-02 03:22 UTC, merged