fix: Use new config when creating special notes
dendronhq/dendron pull request #984
Opened 2021-07-15 07:24 UTC by hikchoi

This PR:
- Fixes issue with journal and scratch note creation configuration still using values from deprecated config location.

related to: #944

2021-07-15 16:47 UTC, kevinslin requested changes
tests please :)

2021-07-19 04:06 UTC, hikchoi commented
- Added test for correct behavior

2021-07-19 17:07 UTC, kevinslin approved these changes

2021-07-19 17:07 UTC, kevinslin approved these changes

2021-07-19 17:08 UTC, merged